article: https://www.bigclown.com/doc/projects/radio-smart-led-strip/
video: https://youtu.be/idxAoc2q6O0
images:
  - title:
    url: https://cdn.myshoptet.com/usr/shop.hardwario.com/user/shop/category_portrait/184-4_power-controller-kit-a1.jpg?5de56e1c
assembly:
  - name: BigClown Cover Module
  - name: BigClown Core Module
  - name: BigClown Power Module
